### ISSUE TITLE
stickergif

### ISSUE THREAD

**Issue by Onlyin2** [SlavyanDesu/BocchiBot#161]
stickergif says files are too large but they're not? what am i supposed to do to get compatibility for any size file

**Comment by SlavyanDesu** [comment]
> stickergif says files are too large but they're not? what am i supposed to do to get compatibility for any size file

Hello. Have you installed the FFmpeg lib?

**Comment by Onlyin2** [comment]
> > stickergif says files are too large but they're not? what am i supposed to do to get compatibility for any size file
> 
> Hello. Have you installed the FFmpeg lib?

yes i did.

**Comment by SlavyanDesu** [comment]
WhatsApp GIF size limit is so very strict which is only 1 MB files are accepted.
You can try to adjust the FPS limit on this line, `10` is a standard FPS for GIFs.
https://github.com/SlavyanDesu/BocchiBot/blob/f5d59275744b214a9618d4189bf3e7e0f955c91b/message/index.js#L2099

**Comment by Onlyin2** [comment]
> WhatsApp GIF size limit is so very strict which is only 1 MB files are accepted.
> You can try to adjust the FPS limit on this line, `10` is a standard FPS for GIFs.
> https://github.com/SlavyanDesu/BocchiBot/blob/f5d59275744b214a9618d4189bf3e7e0f955c91b/message/index.js#L2099

still didn't work, it says "File too large!"
```
`at` C:\Users\*anonymous*\BocchiBot\node_modules\fluent-ffmpeg\lib\capabilities.js:589:21
    at nextTask (C:\Users\*anonymous*\BocchiBot\node_modules\async\dist\async.js:4576:27)
    at next (C:\Users\*anonymous*\BocchiBot\node_modules\async\dist\async.js:4584:13)
    at C:\Users\*anonymous*\BocchiBot\node_modules\async\dist\async.js:321:20
    at C:\Users\*anonymous*\BocchiBot\node_modules\fluent-ffmpeg\lib\capabilities.js:549:7
    at handleExit (C:\Users\*anonymous*\BocchiBot\node_modules\fluent-ffmpeg\lib\processor.js:170:11)
    at ChildProcess.<anonymous> (C:\Users\jaype\BocchiBot\node_modules\fluent-ffmpeg\lib\processor.js:184:11)
```

**Comment by SlavyanDesu** [comment]
Can you send me full logs of the error? I can't reproduce it, mine is working fine. :/
![image](https://user-images.githubusercontent.com/28254882/104676867-d2a92a00-571a-11eb-91bd-8663ac8be6d4.png)

**Comment by Onlyin2** [comment]
> Can you send me full logs of the error? I can't reproduce it, mine is working fine. :/
> ![image](https://user-images.githubusercontent.com/28254882/104676867-d2a92a00-571a-11eb-91bd-8663ac8be6d4.png)

`[0114/100554.353:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-z8JGM9\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/100554.354:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-z8JGM9\Crashpad\reports\00890548-3260-44c5-a337-554e8a3701b3.dmp: The system cannot find the path specified. (0x3)
[0114/100554.354:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/101231.099:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-JvSiZY\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/101231.099:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-JvSiZY\Crashpad\reports\70d46fd7-d738-4324-91f5-71f64d9a889c.dmp: The system cannot find the path specified. (0x3)
[0114/101231.101:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/102428.862:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
[0114/105716.658:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-m2tKFv\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/105716.659:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-m2tKFv\Crashpad\reports\f7e35957-26be-4a0e-af0e-a88b57b336b0.dmp: The system cannot find the path specified. (0x3)
[0114/105716.659:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/105934.751:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-C7FLNj\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/105934.752:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-C7FLNj\Crashpad\reports\4e312606-e103-4f21-b74a-2279e7c86c6e.dmp: The system cannot find the path specified. (0x3)
[0114/105934.752:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/110421.819:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-yoTI9F\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/110421.819:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-yoTI9F\Crashpad\reports\a898b6a0-024c-4ff9-bad2-a088ae9d0766.dmp: The system cannot find the path specified. (0x3)
[0114/110421.819:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/111523.629:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
[0114/114213.688:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-Maiz2m\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/114213.688:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-Maiz2m\Crashpad\reports\0734aad8-f163-414b-b572-3fc8fc26770d.dmp: The system cannot find the path specified. (0x3)
[0114/114213.688:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/115245.766:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
[0114/152346.238:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-UfE0IB\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/152346.238:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-UfE0IB\Crashpad\reports\4aba7f0d-598b-4309-a966-29e25cd6516a.dmp: The system cannot find the path specified. (0x3)
[0114/152346.238:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/154140.815:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
[0114/155008.340:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-aHhZqz\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/155008.341:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-aHhZqz\Crashpad\reports\900eef70-3284-4284-9a6e-04edee559d5b.dmp: The system cannot find the path specified. (0x3)
[0114/155008.341:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
[0114/194023.762:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
[0114/201236.845:ERROR:file_io_win.cc(162)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-oYkLQy\Crashpad\settings.dat: The system cannot find the path specified. (0x3)
[0114/201236.845:ERROR:file_io_win.cc(171)] CreateFile C:\Users\jaype\AppData\Local\Temp\puppeteer_dev_chrome_profile-oYkLQy\Crashpad\reports\fb0bd2fe-112c-4beb-b3ae-1ce87d8de6f1.dmp: The system cannot find the path specified. (0x3)
[0114/201236.845:ERROR:crash_report_exception_handler.cc(99)] PrepareNewCrashReport failed
`

**Comment by SlavyanDesu** [comment]
Can you access the FFmpeg in your terminal? the log says that they can't find the FFmpeg. Access it by typing:
```bash
> ffmpeg
```

**Comment by VideFrelan** [comment]
If you are still having problems, feel free to reopen the issue or you can join the group for a quick response
