### ISSUE TITLE
whats problem help

### ISSUE THREAD

**Issue by HzKEnan** [SlavyanDesu/BocchiBot#428]
[ERROR] Error: Evaluation failed: i
    at ExecutionContext._evaluateInternal (C:\Users\user\Desktop\BocchiBot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\user\Desktop\BocchiBot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

**Comment by Sansekai** [comment]
> [ERROR] Error: Evaluation failed: i at ExecutionContext._evaluateInternal (C:\Users\user\Desktop\BocchiBot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ExecutionContext.evaluate (C:\Users\user\Desktop\BocchiBot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

Update your version open wa.
`npm install @open-wa/wa-automate@latest`
