### ISSUE TITLE
The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.

### ISSUE THREAD

**Issue by TaphT** [SlavyanDesu/BocchiBot#489]
**Question**
Gua mau host bot nya di Pterodactyl tapi ini keluar terus
```
✓ Version: 4.58.0
Erroritializing WA
    at new LauncherError (/home/container/node_modules/chrome-launcher/dist/utils.js:26:22)
    at new ChromePathNotSetError (/home/container/node_modules/chrome-launcher/dist/utils.js:33:9)
    at Object.linux (/home/container/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
    at Launcher.getInstallations (/home/container/node_modules/chrome-launcher/dist/chrome-launcher.js:130:51)
    at /home/container/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:435:65
    at Generator.next (<anonymous>)
    at fulfilled (/home/container/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ChromePathNotSetError
    at new LauncherError (/home/container/node_modules/chrome-launcher/dist/utils.js:26:22)
    at new ChromePathNotSetError (/home/container/node_modules/chrome-launcher/dist/utils.js:33:9)
    at Object.linux (/home/container/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
    at Launcher.getInstallations (/home/container/node_modules/chrome-launcher/dist/chrome-launcher.js:130:51)
    at /home/container/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:435:65
    at Generator.next (<anonymous>)
    at fulfilled (/home/container/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  message: 'The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.',
  code: 'ERR_LAUNCHER_PATH_NOT_SET'
}
```
Gimana cara perbaiki nya

**Comment by SlavyanDesu** [comment]
Coba ganti ke `false` bagian ini.
https://github.com/SlavyanDesu/BocchiBot/blob/c065c4550855153f74ff951aa9a18be6638e56cf/tools/index.js#L76
