### ISSUE TITLE
GMNA OM

### ISSUE THREAD

**Issue by irhanftelis** [SlavyanDesu/BocchiBot#523]
✖ Error launching browser
Error: Failed to launch the browser process!
/home/runner/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/home/runner/BocchiBot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
✖ Failed to launch the browser process!
/home/runner/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

Error: Failed to launch the browser process!
/home/runner/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/home/runner/BocchiBot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Error: Failed to launch the browser process!
/home/runner/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/home/runner/BocchiBot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by SlavyanDesu** [comment]
Install Chrome.

https://openwa.dev/docs/get-started/installation#chrome-issues-on-linux-based-systems

**Comment by irhanftelis** [comment]
tpi gua run di replit bang

**Comment by Piyoxz** [comment]
> tpi gua run di replit bang

replit gabisa , mending rdp 
kalo mau pake replit coba pake library bot wa yang lain

**Comment by irhanftelis** [comment]
Oh gtu ya bang, gapunya rdp hwhw
