### ISSUE TITLE
ERROR file not found

### ISSUE THREAD

**Issue by farizqyy** [SlavyanDesu/BocchiBot#528]
saat beberapa user ingin menggunakan command .profile muncul ERROR
ini isi dari errornya

```
[ERROR] FILE_NOT_FOUND: Cannot find file. Make sure the file reference is relative, a valid URL or a valid DataURL: ERROR: 401
    at C:\Users\mfari\BocchiBot\node_modules\@open-wa\wa-automate\dist\utils\tools.js:399:23
    at Generator.next (<anonymous>)
    at C:\Users\mfari\BocchiBot\node_modules\@open-wa\wa-automate\dist\utils\tools.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mfari\BocchiBot\node_modules\@open-wa\wa-automate\dist\utils\tools.js:27:12)
    at assertFile (C:\Users\mfari\BocchiBot\node_modules\@open-wa\wa-automate\dist\utils\tools.js:376:77)
    at Client.<anonymous> (C:\Users\mfari\BocchiBot\node_modules\@open-wa\wa-automate\dist\api\Client.js:1814:40)
    at Generator.next (<anonymous>)
    at C:\Users\mfari\BocchiBot\node_modules\@open-wa\wa-automate\dist\api\Client.js:31:71
    at new Promise (<anonymous>)
```

**Comment by dskja** [comment]
For me too, The same Erorr

**Comment by SlavyanDesu** [comment]
Sorry, the library itself is dead now.
