### ISSUE TITLE
Bang gw mau minta tolong

### ISSUE THREAD

**Issue by akujeleksad** [SlavyanDesu/BocchiBot#62]
Kirim better-sqlite3 filenya
dri tadi w download ga bisa bisa

**Comment by akujeleksad** [comment]
Pls bang

**Comment by SlavyanDesu** [comment]
https://drive.google.com/drive/folders/1-1q07rAk-y_4BluF7mGvsWISFh0TWgMo?usp=sharing

**Comment by akujeleksad** [comment]
ga

**Comment by akujeleksad** [comment]
C:\BocchiBot-master\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The module '\\?\C:\BocchiBot-master\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (C:\BocchiBot-master\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\BocchiBot-master\node_modules\better-sqlite3\lib\database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)

**Comment by akujeleksad** [comment]
gmn tuh bang

**Comment by SlavyanDesu** [comment]
> gmn tuh bang

coba aja salah satu
```bash
> npm rebuild
```
atau 
```bash
> npm install
```

**Comment by SlavyanDesu** [comment]
btw udah instal visual studio yang latest dengan workload desktop development with c++?

**Comment by SlavyanDesu** [comment]
# Announcement
Silakan update source code ke versi terbaru.
```bash
> git pull orgin master
```

# Changelog
* Mengganti method storing data dari menggunakan `Quick.db` ke JSON array object, karena banyak mengeluh error.
* Register kini hadir dengan model storing yang lebih simpel dengan JSON array object.
* Update string bahasa Inggris.
* Tersedia [group WhatsApp](https://chat.whatsapp.com/LTTm0HGvFRu7uU23mr7ZaR) untuk live support.
* Refactoring.

# Note
Ini akan menghapus data register dan XP/level user, jika kalian tidak ingin menghilangkannya kalian bisa copy data-data tersebut lalu memasukannya lagi secara manual. It can be helped though, sorry.
